### ISSUE TITLE
オンオフスィッチ、OFFのときのデザイン

### ISSUE THREAD

**Issue by yeesamson** [chibidata/dekimashita#1]
増田さんがオン・オフスイッチをつけてくれました。

オフのときに「質問」のフォントの色を薄い灰色に落としましょう。

「送る日時、メールアドレス」を隠して、その代わりに
「だれにもこのメールは送られてません。オンすると配信は再開します。」

![stop](https://cloud.githubusercontent.com/assets/2254390/14080447/2ac1165e-f540-11e5-9918-1074df043f74.png)

そしたら、上にある緑のnotificationはなくてもいいと思います。

<img width="1036" alt="screen shot 2016-03-28 at 11 48 04 pm" src="https://cloud.githubusercontent.com/assets/2254390/14080365/8aeb464a-f53f-11e5-9d23-4dadf2760851.png">

**Comment by saor1** [comment]
できました。

**Comment by yeesamson** [comment]
:+1:
