### ISSUE TITLE
設定されているメールと名前が消えるときがある

### ISSUE THREAD

**Issue by yeesamson** [chibidata/dekimashita#10]
![disappear](https://cloud.githubusercontent.com/assets/2254390/14101865/23d2f6fe-f5d2-11e5-8aaa-2511ad3a773a.gif)

**Comment by yeesamson** [comment]
消えますね。

![2to1](https://cloud.githubusercontent.com/assets/2254390/14134721/04064944-f694-11e5-91ca-b3925193b70e.gif)

**Comment by yoshi-takeda** [comment]
再現しました
これは直さないとまずいですね

こっちで消えたタイミングとしては
アカウントAでログイン→ログアウト→アカウントBでログイン→ログアウト→アカウントAでログイン→この時点で消えた

**Comment by yeesamson** [comment]
アカウントAとBは違う人で同じ端末？

**Comment by yeesamson** [comment]
複数の端末でも、一つしかアカウントしか使わない人には起こらない問題？

**Comment by macha3162** [comment]
Teamの更新時に、入力されたメアドを反映させるために、一旦チームに設定されたメアドを消す処理を入れていたのですが、チームのON/OFFの際にも間違って、同じ処理が動いていました。

ON/OFFするための処理を別処理にしたので、直りました。

**Comment by yoshi-takeda** [comment]
:+1: なおってた！
