### ISSUE TITLE
HTML MAILのデザイン適用

### ISSUE THREAD

**Issue by yeesamson** [chibidata/dekimashita#11]
## 質問：
![question](https://cloud.githubusercontent.com/assets/2254390/14126263/ad0a4d46-f64a-11e5-8207-68c689c568cb.jpg)

## 回答のまとめ：
![app](https://cloud.githubusercontent.com/assets/2254390/14126270/b3bf38fe-f64a-11e5-8fe1-6f1cc0854adf.png)

**Comment by yeesamson** [comment]
アイディアなんですが、名前のとなりメール・リンクをつけることで、まとまったレポートを見て、すぐにコミュニケーションを取れるというのはどうかね。名前のとなりにCommentという名のメール・リンク。

![comment](https://cloud.githubusercontent.com/assets/2254390/14125930/c51dc9f0-f648-11e5-8986-88290fb6b5c8.png)

**Comment by yoshi-takeda** [comment]
前回もらってたデザインは反映済みです
本番で確認できますのでなにかあれば書いてくださいませ

>名前をメール・リンク
これまだ未反映なので、時間出来たら入れます

**Comment by yeesamson** [comment]
![matome](https://cloud.githubusercontent.com/assets/2254390/14137666/c84286b0-f6a3-11e5-8ec0-562c2c54483d.png)

SVG: https://app.box.com/s/akahajl5xfhzjqf3y7n2svlkmn618iwu

**Comment by saor1** [comment]
iPhoneのoutlookのズレ調整の結果真ん中寄せが難しそうなので、本文を左寄せにしました！

**Comment by yeesamson** [comment]
ズレを直すのに時間かかりそうだったので、かなりシンプルになりました。まとめメールはまだ確認できてないが、要素だけ入れてもらえますか。

ニックネーム (mailto:リンク）回答日時

メールの一番下にいま dekimashita.comとありますが、管理者のメールアドレス+より がほしいです。

もし入るなら 5人中3人回答しました。をお願いします。これで以上です

**Comment by yoshi-takeda** [comment]
・ニックネーム (mailto:リンク）
・管理者のメールアドレスより
・回答時間を書く
・5人中3人回答しました
これやります

**Comment by yoshi-takeda** [comment]
https://github.com/chibidata/dekimashita/issues/24

**Comment by yoshi-takeda** [comment]
・管理者のメールアドレスより
・回答時間を書く
![image](https://cloud.githubusercontent.com/assets/10205763/14165902/2dea1690-f749-11e5-98a3-5f00b7545fc7.png)

**Comment by yoshi-takeda** [comment]
・ニックネーム (mailto:リンク）
・5人中3人回答しました
反映
![image](https://cloud.githubusercontent.com/assets/10205763/14166122/6c038af4-f74b-11e5-8991-328d571bced2.png)

**Comment by yoshi-takeda** [comment]
対応終わったのでこいつは閉じまーす
何かあれば別チケットで。
