### ISSUE TITLE
モバイル対応・・

### ISSUE THREAD

**Issue by saor1** [chibidata/dekimashita#14]

**Comment by saor1** [comment]
モバイル画面ではみ出さないように変更
![screen shot 2016-03-30 at 4 25 25 pm](https://cloud.githubusercontent.com/assets/9836255/14134735/17a78c2e-f694-11e5-8053-d65a7df91a84.png)

**Comment by yeesamson** [comment]
携帯でも全ページきれいに見えるようになりました。ありがとう！
