### ISSUE TITLE
google認証用アプリ名が怪しい

### ISSUE THREAD

**Issue by yoshi-takeda** [chibidata/dekimashita#15]
今は開発用なので正式リリース前に取り直す
dekimashita　など。

![image](https://cloud.githubusercontent.com/assets/10205763/14158547/a12434da-f70b-11e5-8736-270534127b0d.png)

**Comment by macha3162** [comment]
対応します。

**Comment by macha3162** [comment]
![2016-03-31 8 24 56](https://cloud.githubusercontent.com/assets/359262/14160883/6cebbdc8-f71a-11e5-9c71-19ef627ca180.png)
対応しました。
画面の画像は、http://app.dekimashita.com/matome.png を利用しています。

**Comment by yeesamson** [comment]
あっ、ロゴは白黒のほうが公式です。

すみません。色つきはまとめメールだけ。

**Comment by macha3162** [comment]
差し替え完了です。
https://security.google.com/settings/security/permissions?hl=ja
GoogleDashboardからアプリの接続を切ると確認できます。

![2016-03-31 8 44 06](https://cloud.githubusercontent.com/assets/359262/14161201/ca4a0662-f71c-11e5-8c0f-24ca3039ac10.png)

**Comment by yoshi-takeda** [comment]
good job !!
