### ISSUE TITLE
チームメンバーのメールアドレスの重複チェック

### ISSUE THREAD

**Issue by yoshi-takeda** [chibidata/dekimashita#16]
重複して登録したいユースケースは想定されないので、本リリースまでに入れる
![image](https://cloud.githubusercontent.com/assets/10205763/14159550/69c71c86-f711-11e5-9125-a7e54cf1999c.png)

**Comment by macha3162** [comment]
アドレスが消える件と合わせてみます。

**Comment by yoshi-takeda** [comment]
今はそんなに困らないので、あとまわし。

**Comment by macha3162** [comment]
アドレスが消える件は、別件で対応済み。
重複の件を対応しました。

**Comment by yeesamson** [comment]
@macha3162 重複チェックはもう入ってるってことでしょうか。

**Comment by yoshi-takeda** [comment]
![image](https://cloud.githubusercontent.com/assets/10205763/14707106/a31448f4-07fd-11e6-95b3-ed024c9e95e3.png)

はいってました。ナイス
