### ISSUE TITLE
チームメンバーの入力欄の自動拡張

### ISSUE THREAD

**Issue by yoshi-takeda** [chibidata/dekimashita#17]
本リリースまでに。

今は保存しないと増えないので手間が大きい
同画面内で自動で増えるようにするか、テキストエリアに変える（簡単な方で
![image](https://cloud.githubusercontent.com/assets/10205763/14159649/dea7336a-f711-11e5-8523-0564e28026d1.png)

**Comment by macha3162** [comment]
追加ボタン付けときます

**Comment by yoshi-takeda** [comment]
よろしく :+1:

**Comment by yoshi-takeda** [comment]
ggood!!
