### ISSUE TITLE
案：メンバー一覧にニックネームも出すのはどう？

### ISSUE THREAD

**Issue by yoshi-takeda** [chibidata/dekimashita#18]
ニックネームも出すと分かりやすいと思いました
![image](https://cloud.githubusercontent.com/assets/10205763/14159790/fa5949b2-f712-11e5-9e3d-b19d512eaf56.png)

**Comment by yeesamson** [comment]
メールアドレスをやめて、ニックネームだけにしましょう。

**Comment by yoshi-takeda** [comment]
たいおうしときまーす :+1:

**Comment by yeesamson** [comment]
> 
<img width="636" alt="screen_shot_2016-03-31_at_12_44_47" src="https://cloud.githubusercontent.com/assets/2254390/14164898/aeac5532-f73e-11e5-91ac-7b903be1feff.png">

**Comment by saor1** [comment]
#7 のデザインでメンバーリストをメルアドから名前に変更しました。名前がなければemailを出しています。
メンバーは登録するときに名前が必須入力になったので名前で出ていて、
オーナーは別のDB項目（Userテーブル）からとってます。google認証の時に名前があれば入って、なければ入らないみたいになってる項目だと思います。

**Comment by yeesamson** [comment]
オッケーオッケー！ありがと。

**Comment by yoshi-takeda** [comment]
:ok_hand:
