### ISSUE TITLE
回答できない時間に返信した場合に送られるメールを綺麗にする

### ISSUE THREAD

**Issue by yoshi-takeda** [chibidata/dekimashita#20]
なんでそうなるのかちゃんと書く
![image](https://cloud.githubusercontent.com/assets/10205763/14159982/51f622e8-f714-11e5-9ed8-7eeb401b9e31.png)

**Comment by yeesamson** [comment]
ここもほかの二つのメールができたらデザイン適用したいですね。

**Comment by yoshi-takeda** [comment]
文言修正だけはやっときました

なんか、受け付けてない感がある、おつかれ山の画像がほしいですね

**Comment by yeesamson** [comment]
![dekimasendeshita](https://cloud.githubusercontent.com/assets/2254390/14491244/ab141756-01b2-11e6-8458-e557380966a0.png)

**Comment by yoshi-takeda** [comment]
見逃してた。僕の方で対応します

**Comment by yeesamson** [comment]
お願いします。

**Comment by yoshi-takeda** [comment]
done
![image](https://cloud.githubusercontent.com/assets/10205763/14770755/350a642e-0ab4-11e6-8329-714a71ecc43b.png)
