### ISSUE TITLE
質問メールに受付時間

### ISSUE THREAD

**Issue by yeesamson** [chibidata/dekimashita#24]
質問メールに受付時間がないね。
何時に配信予定だからそれまでに返信してください的な。

設定変更できるので、あくまで質問メールを配信した時点でのまとめメール配信予定時間になるが、それはいりいますね。

![timelimiti](https://cloud.githubusercontent.com/assets/2254390/14165409/9331e826-f743-11e5-9899-3e2ca38cdfa8.png)

**Comment by yoshi-takeda** [comment]
https://github.com/chibidata/dekimashita/issues/11
こちらで対応済み
