### ISSUE TITLE
左右ボタンよりビッグボタンのほうが指に優しい。

### ISSUE THREAD

**Issue by yeesamson** [chibidata/dekimashita#27]
![bigbutton](https://cloud.githubusercontent.com/assets/2254390/14199453/7d55bfe6-f81f-11e5-82b1-6b7b4bff33f5.jpg)

**Comment by saor1** [comment]
設定画面と日報編集画面の二箇所に反映しました。
![screen shot 2016-04-01 at 4 46 28 pm](https://cloud.githubusercontent.com/assets/9836255/14200920/4e8ad7c8-f829-11e5-8166-6518b89f10bc.png)
