### ISSUE TITLE
文言修正

### ISSUE THREAD

**Issue by yeesamson** [chibidata/dekimashita#29]
<img width="682" alt="screen_shot_2016-04-01_at_17_13_33" src="https://cloud.githubusercontent.com/assets/2254390/14201473/236c1684-f82d-11e5-9737-ff41ffa583e3.png">

#### AFTER
![question](https://cloud.githubusercontent.com/assets/2254390/14201476/271f418e-f82d-11e5-9675-5847a13f84e2.png)

**Comment by saor1** [comment]
変更しときました。
![screen shot 2016-04-01 at 5 29 27 pm](https://cloud.githubusercontent.com/assets/9836255/14201825/4fa5ce64-f82f-11e5-9845-424d02246d9a.png)

**Comment by yoshi-takeda** [comment]
津田さんが東京戻ったときにコミットする

**Comment by yeesamson** [comment]
オッケー

**Comment by saor1** [comment]
コミットしました！

**Comment by yoshi-takeda** [comment]
はいってました 👍
