### ISSUE TITLE
画面右上にあるlogoutボタンを画面左下のフッターに

### ISSUE THREAD

**Issue by yeesamson** [chibidata/dekimashita#3]
### 1. 画面右上にあるlogoutボタンを画面左下のフッターに。
（そうしないと携帯で見たときにログアウトボタンがずれる）

新しいフッター：Made with ♥ by elli.io - logout

![asset](https://cloud.githubusercontent.com/assets/2254390/14080175/4da6c008-f53e-11e5-8c33-a64bbb86a69e.png)

**Comment by saor1** [comment]
できました！

**Comment by yeesamson** [comment]
:+1:
