### ISSUE TITLE
カレンダーから配信日を予約

### ISSUE THREAD

**Issue by yoshi-takeda** [chibidata/dekimashita#31]
忘れないようにチケットだけ作成

**Comment by yeesamson** [comment]
<img width="307" alt="screen shot 2016-04-13 at 7 43 54 pm" src="https://cloud.githubusercontent.com/assets/2254390/14490816/124375aa-01b0-11e6-8590-3207f1121f3e.png">


文言：
設定がなければ自動的平日に送られます。
平日以外の配信日を選ぶ

**Comment by yeesamson** [comment]
@macha3162 
このとき週末を開放させることは可能でしょうか。飲食ですね。

**Comment by macha3162** [comment]
可能です。

**Comment by yeesamson** [comment]
@macha3162 
考えてみるとバイトってそれぞれ勤務する日が違いますね。

いまある平日毎日以外に対応したいのって週報だと思います。週報がメイン。そこから欲張ってカレンダーから選べれば、週報もいろんなのに対応できるんじゃないかって話しになった。

計画性のない悪いパターンですね。

一度増田さんと話して、いまのシステムはどういう仕組みで、どういうことなら可能か話したいです。明日少し時間をいただけますでしょうか。すみません。

**Comment by yoshi-takeda** [comment]
これそもそもターゲットは誰ですか？

**Comment by yeesamson** [comment]
当初のターゲットは新卒でした。Gambaのセミナーに参加して、リヴァンプとも話したところ飲食には日報問題も深刻で、需要はあります。

週報の重要が見えてきたところで、解決方法としてカレンダーで日指定するならできるって話しになって、それを進めているところ。

本当はこうしたいけど、工数かかるので、ここまでならできるという決断をしてしまったのが、今回の問題を起こしてると思います。申し訳ない。

何を作るのかの共通認識を持つことはやはり大事で、絵がないのに開発を進めるのは辞めましょう。どんなに小さなことでも新しいものを作るときはきちんとハングアウトして話しましょう。

**Comment by yoshi-takeda** [comment]
過程の共有ありがとうございます！
なんとなくオフィス作業者をイメージしてましたが、思ったより多くの業界で需要があるんですね
確かに携帯のメールへの返信なら特にハードルはないですもんね

**Comment by yeesamson** [comment]
![pickdays](https://cloud.githubusercontent.com/assets/2254390/14547296/19d782ce-02e7-11e6-9379-c5b1b58bb328.png)

こういうイメージかね。

**Comment by yoshi-takeda** [comment]
・質問メールを送る曜日：人ごとに指定したい
　→シフト勤務を考慮

・質問、まとめメールを送る時間：チーム単位で指定したい

ってことかな。それだとそのイメージで満たせますね

あとは少し話しに出てた、定期じゃなくて
単発で送るようなものはいったんカバーしない方針ですか？

**Comment by macha3162** [comment]
いえ、違います。
人ごとに配信日を設定できる想定はなく、チームとして
 * 平日の指定した時刻に送る
 * 選択した日程(土日含む)の指定した時刻に送る

だと思っておりましたので、以下の動きで作っていました。
## 平日に送信
![2016-04-15 8 56 22](https://cloud.githubusercontent.com/assets/359262/14547399/082be348-02e8-11e6-807a-3158069352a1.png)

## 選択日に送信(1つのカレンダーで複数日選択可能です)
![2016-04-15 8 56 34](https://cloud.githubusercontent.com/assets/359262/14547412/23b5d826-02e8-11e6-89a1-f1ac1016b0bc.png)

**Comment by macha3162** [comment]
曜日指定に仕様が変更されました。
デザイン反映は別チケットであるため #42 Closeします。
