### ISSUE TITLE
メンバーのメールアドレス入力支援　input type=email

### ISSUE THREAD

**Issue by yeesamson** [chibidata/dekimashita#33]
これができれば、Google Contactsをやるまでもないかもしれない。

<img width="828" alt="screen_shot_2016-04-11_at_14_18_27" src="https://cloud.githubusercontent.com/assets/2254390/14417459/d8a534ac-fff0-11e5-9dfc-b2abb80b073a.png">

![asset-1](https://cloud.githubusercontent.com/assets/2254390/14417461/da451c50-fff0-11e5-8b4c-262b0d0eb78a.jpg)

**Comment by saor1** [comment]
変更しました！

**Comment by yeesamson** [comment]
![slack_for_ios_upload](https://cloud.githubusercontent.com/assets/2254390/14490743/9d7b4072-01af-11e6-9c3f-e55d854cb930.jpg)

ありがとう！
