### ISSUE TITLE
平日から「祝日」を除外する

### ISSUE THREAD

**Issue by yeesamson** [chibidata/dekimashita#34]
@macha3162 回答がないとき、まとめメールを送信しないのって実装済み？

質問メールもまとめメールも平日の祝日には送らないようにできるか。

https://github.com/komagata/holiday_jp

![calendar3-1](https://cloud.githubusercontent.com/assets/2254390/14491312/040b84fc-01b3-11e6-91b7-7f028e822294.gif)

**Comment by macha3162** [comment]
祝日は考慮していません。
対応は可能ですが、祝日マスターのメンテナンスが必要になりそうです。

**Comment by yeesamson** [comment]
了解です。優先度高くはないと思います。２０１６年に祝日と呼ばれる日はたったの１６日になります。
