### ISSUE TITLE
管理者本人のメールもオプションにする。

### ISSUE THREAD

**Issue by yeesamson** [chibidata/dekimashita#36]
これまで質問メールもまとめメールも自動的に管理者本人に送られてましたが、それではGoogle appsを使ってない会社では使えない（Gmailで登録、Gmailに送るとまずい。機密問題）。

管理者本人のメールアドレスがデフォルトではメンバーの一人として登録されていて、それが削除できればクリアし、ヤフーでもすぐに使ってもらえます。

![screen-shot-2016-04-14-at-14_30_07](https://cloud.githubusercontent.com/assets/2254390/14518030/a9798254-024e-11e6-8a32-c5f9d68581b3.jpg)

**Comment by yeesamson** [comment]
<img width="751" alt="screen_shot_2016-04-14_at_14_43_47" src="https://cloud.githubusercontent.com/assets/2254390/14518088/5b549f7c-024f-11e6-8c26-c25b5bc767f1.png">

**Comment by macha3162** [comment]
対応が完了しました。
自分自身もメンバーとして選択できるよう、初期値として入るようにしております。

![dekimashita](https://cloud.githubusercontent.com/assets/359262/14519206/56feb9d6-0258-11e6-8c33-10708bab06f2.png)

**Comment by yeesamson** [comment]
ありがとうございます！
