### ISSUE TITLE
チームごとに質問メールの送信曜日を指定できるようにする

### ISSUE THREAD

**Issue by yoshi-takeda** [chibidata/dekimashita#37]
今は自動的に平日のみ送る　としているが
チームごとに何曜日に質問メールを送るのかを指定できるようにする

これによって、週1だけ送って週報として使うなど、使いみちが広がる

![artboard 2](https://cloud.githubusercontent.com/assets/2254390/14549062/6b1ab7ea-02f7-11e6-8ebf-4bc4ddb2057b.png)

**Comment by macha3162** [comment]
見た目は不完全ですができました。
Unitテストで動作確認してますが、実際の動作確認もしておきたい。

**Comment by yoshi-takeda** [comment]
この設定でサイクルテストしときます
![image](https://cloud.githubusercontent.com/assets/10205763/14552935/8f094ec0-031d-11e6-9e1f-cd04bc5b1a1f.png)

**Comment by yoshi-takeda** [comment]
土日サイクルテスト問題なしでした
