### ISSUE TITLE
レポートの送り先を追加指定できるようにする

### ISSUE THREAD

**Issue by yoshi-takeda** [chibidata/dekimashita#39]
今は管理者とチームメンバーに送られるが
その宛先をチームごとに増やせるようにする。

行ってきました　の最後の画面にある上司に送る欄と同じようなイメージ

![artboard 2](https://cloud.githubusercontent.com/assets/2254390/14549213/f3b86056-02f8-11e6-8610-960597269e3c.png)

**Comment by macha3162** [comment]
レポートの送り先のアドレスを1つ指定できるようにしました。
話では、カンマ区切りで複数と言っていましたが、見た目も中身も入力も複雑になるので、
シンプルにメアド1個入れれるようにしてます。

<img width="512" alt="2016-04-15 15 05 39" src="https://cloud.githubusercontent.com/assets/359262/14552696/8c112dac-031b-11e6-8187-bda6fd83ba19.png">

**Comment by yoshi-takeda** [comment]
設定したアドレスに、ちゃんとまとめメールきてました
