### ISSUE TITLE
エラーがあるときだけ、メールアドレスとニックネームが二行になってしまう。

### ISSUE THREAD

**Issue by yeesamson** [chibidata/dekimashita#4]
<img width="773" alt="screen_shot_2016-03-28_at_11_31_59_pm" src="https://cloud.githubusercontent.com/assets/2254390/14080035/577db6b4-f53d-11e5-8d79-c8c452395d71.png">

**Comment by saor1** [comment]
変更しました。
![screen shot 2016-03-29 at 2 43 52 pm](https://cloud.githubusercontent.com/assets/9836255/14099026/d8b79180-f5bc-11e5-8d87-c81740ef37e5.png)

**Comment by yeesamson** [comment]
:+1:
