### ISSUE TITLE
管理者が複数チームを作れるようにする

### ISSUE THREAD

**Issue by yoshi-takeda** [chibidata/dekimashita#40]
今は1チーム固定

複数チームを作れるようにすることで
複数の組織をカバーできたり、複数の送信体系(日報用、週報用など)を管理したりと
と使いみちが広がる

**Comment by yeesamson** [comment]
![artboard 2](https://cloud.githubusercontent.com/assets/2254390/14549199/d6515cb6-02f8-11e6-8457-e9a1853b0635.png)

**Comment by macha3162** [comment]
着手します

**Comment by macha3162** [comment]
できました
