### ISSUE TITLE
UI微調整：曜日のチェックボックス

### ISSUE THREAD

**Issue by yeesamson** [chibidata/dekimashita#42]
曜日の漢字とチェック・ボックスを一つにすることは可能でしょうか。

<img width="563" alt="8b524c02-0334-11e6-98c1-8afb3527247f" src="https://cloud.githubusercontent.com/assets/2254390/14557088/77bfae9e-0336-11e6-8f80-d822bc5e1d19.png">

![9d6f7202-0334-11e6-8607-bddfbd6a1d4c](https://cloud.githubusercontent.com/assets/2254390/14557092/798d80ac-0336-11e6-82ce-fe0ff88cb62e.png)

![weekdays](https://cloud.githubusercontent.com/assets/2254390/14557261/5328c736-0337-11e6-8bfa-a32bc5d2d9e8.gif)

**Comment by saor1** [comment]
Bootstrapのチェックボックスボタンをそのまま使ったけど、
個人的にはどっちがONでどっちがOFFかちょっとわかりにくい。。
![screen shot 2016-04-20 at 5 48 30 pm](https://cloud.githubusercontent.com/assets/9836255/14668623/222dd27e-0720-11e6-90d0-126958dd506a.png)

**Comment by yeesamson** [comment]
ついてるときは青、ついてないときはグレーなイメージ。

![days](https://cloud.githubusercontent.com/assets/2254390/14668764/caa64850-0720-11e6-99e4-2725bbf66880.png)

**Comment by saor1** [comment]
修正しました
<img width="33" alt="screen shot 2016-04-20 at 6 08 08 pm" src="https://cloud.githubusercontent.com/assets/9836255/14669223/dd2501fe-0722-11e6-9503-70ccd7094cd3.png">
![screen shot 2016-04-20 at 6 06 57 pm](https://cloud.githubusercontent.com/assets/9836255/14669200/c1751c1e-0722-11e6-8163-b8a260e7e53b.png)

**Comment by yoshi-takeda** [comment]
確認しました👍
