### ISSUE TITLE
設定画面などの上限値を記載する

### ISSUE THREAD

**Issue by yoshi-takeda** [chibidata/dekimashita#44]
・メンバーの追加数
・文字数
など

**Comment by yeesamson** [comment]
@macha3162 実際いま制限は設けてないでしょうか。

**Comment by macha3162** [comment]
文字数は、入力できるところは255文字
チーム数、メンバー数に制限は設けておりません。

**Comment by yeesamson** [comment]
@macha3162 ありがとう。津田さんにお願いして画面に記載するようにしましょう。

**Comment by saor1** [comment]
■今の仕様はこうなりました
・1アカウントでチーム10件まで
・1質問にメンバーは30件まで
・質問は255文字まで

上限数を明記。
30件超えると「もっと入力する」が消えて「メンバーの上限は30件までです」の文字が出ます。
![dekimashita](https://cloud.githubusercontent.com/assets/9836255/14664319/ef864c68-0704-11e6-9367-3f3eebf12f16.png)


チーム上限を超えると新しい質問入力画面に行かない。
![screen shot 2016-04-20 at 2 28 09 pm](https://cloud.githubusercontent.com/assets/9836255/14664324/f39c8952-0704-11e6-93a6-856ad18f4b40.png)

**Comment by yeesamson** [comment]
３つの上限があります。
メンバー数は実際３０人以上を登録しようとするときに警告が出ますので、はじめっから主張しなてくもよいかと。

チームではなく「質問数」と「質問の文字数」に関しても越えるときに表示させましょう。

<img width="780" alt="97113202-0707-11e6-98dd-4068ac189dcb" src="https://cloud.githubusercontent.com/assets/2254390/14664701/29dfccec-0708-11e6-86cb-648aeaf56d4c.png">

**Comment by saor1** [comment]
サムソンがうえのキャプチャで矢印つけてる３つの表示を削除しました。

入力エラーの表示は元からあったこれが出ます。
![screen shot 2016-04-20 at 2 58 01 pm](https://cloud.githubusercontent.com/assets/9836255/14665409/f5651db8-070d-11e6-93c7-1caadeccc98f.png)

「メンバーを追加」リンクは上限数（３０）を超えると「メンバーの上限は30人までです」のテキストに変わります。

**Comment by yoshi-takeda** [comment]
ステージングで確認しました 🆗
