### ISSUE TITLE
ステータスページの作成

### ISSUE THREAD

**Issue by yoshi-takeda** [chibidata/dekimashita#45]

**Comment by yeesamson** [comment]
ステータスページはいま正常に動いてますというページ？

**Comment by yoshi-takeda** [comment]
そうです
以下の2つの質問を満たすためですね
>インシデント対応についての情報提供の方針を定め、公表しているか。
>システムの障害履歴が公開されているか。
解答例だと https://status.slack.com/ が挙げられてる

**Comment by yeesamson** [comment]
@yoshi-takeda 増田さんが試しに作ってくれたやつは無料のままで使えそう？

**Comment by yoshi-takeda** [comment]
はい、問題なさそうなんでこれでやってみます

https://elements.heroku.com/addons/statushub
http://dekimashita.statushub.io/

**Comment by yoshi-takeda** [comment]
heorkuからAWSに移行することで無料ではなくなるので使用しない
5月時点では無料前提で静的なページで公開するが
そのままだと確実に運用が回らないのでどこかで切り替える

**Comment by yoshi-takeda** [comment]
静的なページは適当なテンプレートを使って僕の方でアップします

**Comment by yeesamson** [comment]
![status](https://cloud.githubusercontent.com/assets/2254390/14732861/5d34044a-0899-11e6-927e-fdc5d229c2e4.png)

デザイン案。

**Comment by yoshi-takeda** [comment]
サムソンデザイン案を元に静的ページを作成
津田さんアサイン

**Comment by yoshi-takeda** [comment]
サブドメインを切って本体とドメインを分ける

**Comment by yeesamson** [comment]
![status](https://cloud.githubusercontent.com/assets/2254390/14772352/287dc86c-0ad8-11e6-8a3f-709c4486b823.png)

**Comment by saor1** [comment]
dekimashitaソース内にstatus_pageというフォルダを作って、そこにHTML一式を置きました。

**Comment by yoshi-takeda** [comment]
ありがとうございました！！！
こちらでアクセスできます
http://status.dekimashita.com/

S3上の「status.dekimashita.com」バケット内のファイルを更新すると内容が更新されます
https://console.aws.amazon.com/s3/home?region=ap-northeast-1#&bucket=status.dekimashita.com&prefix=

**Comment by saor1** [comment]
ありがとうございます！
