### ISSUE TITLE
退会機能

### ISSUE THREAD

**Issue by yoshi-takeda** [chibidata/dekimashita#47]
管理者がdekimashitaの利用をやめる機能
・認証情報、レポートデータなど関連データを全て削除
・google、facebook側の連携情報の削除

**Comment by macha3162** [comment]
機能としては実装しました。
ボタンどこにつけましょ。

**Comment by macha3162** [comment]
ガイドに退会するためのフローを設けました。
![2016-04-20 10 42 41](https://cloud.githubusercontent.com/assets/359262/14660944/a44ee3c4-06e4-11e6-9817-889dcb37c17b.png)

**Comment by yeesamson** [comment]
ありがとうございます。どのアカウントから退会してるのかが知りたいのと、終わったらいまはトップページに戻っていますが、お礼を言いましょう。

<img width="1078" alt="screen_shot_2016-04-20_at_11_17_09" src="https://cloud.githubusercontent.com/assets/2254390/14661573/9c9515f4-06e9-11e6-9d42-1452327bf9f6.png">

ログインしてなくても、退会ボタンが押せて、削除しますかと出るので、少し混乱するかもしれない。

**Comment by yeesamson** [comment]
<img width="1177" alt="screen_shot_2016-04-20_at_11_15_26" src="https://cloud.githubusercontent.com/assets/2254390/14661744/171f0464-06eb-11e6-85a8-7671002ca7a3.png">

https://dekimashita-stg.herokuapp.com/support

ガイドはサインインしていても、サインインしてなくても見れるので、いまのやり方だと混乱すると思います。

それぞれ表示するメッセージを変えることは可能でしょうか。

サインインしてない人：
退会するには
dekimashitaを退会するには、まずログインして、ガイドページにある「退会するには」をクリックしてください。退会時には、メールアドレスを含む、すべての情報がシステムから削除されます。

サインインしている人：
退会するには

dekimashitaを退会するには、こちらをクリックしてください。退会時には、メールアドレスを含む、すべての情報がシステムから削除されます。


表示する場所と文言はこっちでつめます。ありがとう。

**Comment by yeesamson** [comment]
![support](https://cloud.githubusercontent.com/assets/2254390/14662014/61e03426-06ed-11e6-96c2-5b122a7f189c.png)

ガイドにからはトル。一言、「セキュリティについて」に加えることにしましょう。

ドメインのとこを見ると分かるようにdekimashitaはSSLを取得しており、すべての通信は暗号化されています。また送っていただいた日報は２４時間内にまとめメールとしてメンバーに配信し、システムから削除されます。

退会はサポートページの下にある「登録されたアカウントを削除する」をクリックしてください。退会時には、メールアドレスを含む、すべての情報がシステムから削除されます。

**Comment by yeesamson** [comment]
ありがとう。

<img width="1252" alt="screen shot 2016-04-20 at 16 35 01" src="https://cloud.githubusercontent.com/assets/2254390/14666673/e170c836-0715-11e6-8baa-d43bfb01a4d5.png">
