### ISSUE TITLE
そのほかの微調整

### ISSUE THREAD

**Issue by yeesamson** [chibidata/dekimashita#5]
1. ページタイトル：Done → dekimashita
2. ログインページにnotification「Please login first」をトル
2. 平日10:00、平日11:00など、分のドロップダウンをなくす。デフォルト時間は18:00と08:00
3. 保存とキャンセルボタン、左右入れ替え。
![settings](https://cloud.githubusercontent.com/assets/2254390/14080283/feb9bbfc-f53e-11e5-959d-93962b87a944.jpg)

**Comment by saor1** [comment]
できました。
![screen shot 2016-03-29 at 4 25 25 pm](https://cloud.githubusercontent.com/assets/9836255/14100781/ddcda214-f5ca-11e5-8f61-30d1e803859d.png)
時刻選択はrailsの機能を使っていて、「時：分」にまとめるいい方法がみつからなかったのでJSで表示後にそれっぽくしています。

**Comment by yeesamson** [comment]
あとはこれだけですね。
ログインページにnotification「Please login first」をトル

![screen_shot_2016-03-29_at_17_21_03](https://cloud.githubusercontent.com/assets/2254390/14101931/a5a4b956-f5d2-11e5-9232-b7958e6aa4d4.png)

**Comment by saor1** [comment]
取りました◎

**Comment by yeesamson** [comment]
ありがと。
