### ISSUE TITLE
青い説明文の修正

### ISSUE THREAD

**Issue by saor1** [chibidata/dekimashita#51]
編集画面にあった青い文章を質問一覧の青い文字と差し替えて、編集画面には青い文字なしにましょう。　by Samson
![artboard_2](https://cloud.githubusercontent.com/assets/9836255/14665480/7f503580-070e-11e6-8651-2302020e99fb.png)

**Comment by saor1** [comment]
完了です。
１）トップページの説明文差し替え
２）新規登録画面の説明文トル
３）設定編集画面の説明文トル

**Comment by yoshi-takeda** [comment]
オッケーでした！
