### ISSUE TITLE
SLAの作成、明示

### ISSUE THREAD

**Issue by yoshi-takeda** [chibidata/dekimashita#58]
こういう感じ
無料なので料金系は不要
http://support.smaregi.jp/administration/2013060170.php

サポート体制
お知らせ・通知連絡網
サービス時間・性能基準に関する規定
サーバー構成について
バックアップとリカバリー
セキュリティ

**Comment by yeesamson** [comment]
サポート体制はヘルプページ、twitter、コンタクトフォーム
お知らせはメールで
SLAの明示

**Comment by yoshi-takeda** [comment]
増田さんと実現性を判断して、枠を埋めていきます

**Comment by yoshi-takeda** [comment]
リスク分析読んでたら参考としてあった総務省の基準を元に必要な項目と値を確定
http://www.soumu.go.jp/main_sosiki/joho_tsusin/top/local_support/pdf/cio_text18_ps_6.pdf

------------------------------

**サーバーの稼働**
・稼働率
　年単位で99%以上

・対象範囲
　dekimashita.comのウェブサービス

・SLAの適用外
　メールサーバー(適時必要なときに起動と停止を行っているため)

**サーバーの構成**
・サーバー構成全体図
　簡易な図を作る（増田さん情報渡す→サムソンが作成）
　こういうやつ
![image](https://cloud.githubusercontent.com/assets/10205763/14777753/200c3862-0b0a-11e6-8aad-45d1d5d98b46.png)


・サーバー会社
　すべてアマゾン ウェブ サービス（AWS）上に構築し運用
　単一のアベイラビリティゾーンではなく、２つ以上のゾーンに分散して配置している

**バックアップ**

・データは7日間バックアップされており、いつでもリストア可能

**セキュリティ**

・会社としての取り組み
　ISMS（情報セキュリティー）基本方針を定め、運用しております。
　https://www.synergy-marketing.co.jp/company/profile/security/
　第三者機関による監査により、以下の認定を取得しております。
　プライバシーマーク：認証番号：20000604（06）
　ISMS(JIS Q 27001)：登録番号：509862ISMS

・業務フロー
　以下の運用ルールとなっております。
　https://www.synergy-marketing.co.jp/company/profile/security/faq/

**Comment by yoshi-takeda** [comment]
ステータスページの下にくっつけてみます

**Comment by yoshi-takeda** [comment]
ステータスページの下につらつらと貼り付けましたのでこっちの作業は完了。
サーバー構成図はミニマムでは一旦不要　※必要と言われたら貼ります
![image](https://cloud.githubusercontent.com/assets/10205763/14807476/da1295dc-0bb7-11e6-95ba-3053c98d4382.png)
