### ISSUE TITLE
サインアップとサインオンと区別

### ISSUE THREAD

**Issue by yeesamson** [chibidata/dekimashita#59]
dekimashitaにはサインアップとサインオンという区別をしていない。多くのユーザーにとって「新しい」体験になります。

もっと分かりやすいラベリングにしましょう。

Sign with Google→Googleを使う
Sign with facebook→facebookを使う

![login](https://cloud.githubusercontent.com/assets/2254390/14716186/c7d2b616-0826-11e6-93e2-07dbec62dc30.png)

**Comment by yeesamson** [comment]
サインアップ後、「いまのは何だった」のか説明してあげるだけでも全然違います。

![save](https://cloud.githubusercontent.com/assets/2254390/14716568/850a2c86-0828-11e6-9cfb-171f26f7a572.jpg)

#### 理想はこの安心感です。

ライトな方法
![fb](https://cloud.githubusercontent.com/assets/2254390/14716474/2bb663ca-0828-11e6-8224-d30ba22b06eb.png)
![google](https://cloud.githubusercontent.com/assets/2254390/14716475/2bba04bc-0828-11e6-95b6-6351922e253b.png)

安心＋
![safe](https://cloud.githubusercontent.com/assets/2254390/14716807/94b625ee-0829-11e6-8815-535c0bd63566.png)

**Comment by saor1** [comment]
ログインしました画面を追加しました
![screen shot 2016-04-22 at 11 50 11 am](https://cloud.githubusercontent.com/assets/9836255/14730322/66ba7b98-0880-11e6-9655-cbd47fdb246c.png)

![screen shot 2016-04-22 at 11 51 14 am](https://cloud.githubusercontent.com/assets/9836255/14730341/889f33fc-0880-11e6-8d29-bfb158866680.png)

**Comment by saor1** [comment]
文言をサインアップしました。に変更しました。
この画面はサインアップ時のみ表示し、二回目以降のログイン時には出ません。

**Comment by yeesamson** [comment]
ありがとう！

これでGoogle と facebookでのサインアップの不安はだいぶ解消されます。
あとはボタンのラベルもお願いします。

話してみて、「Googleを使う」、「Facebookを使う」は意味分からないとのことなので、いまある英語表記から、「Googleでログイン」、「Facebookでログイン」に変えましょう。

**Comment by saor1** [comment]
ログイン画面も修正しました。
グレーの小さい文字のところは規約ページができてから変更でいいと思います
![screen shot 2016-04-22 at 12 42 58 pm](https://cloud.githubusercontent.com/assets/9836255/14731044/c661cc34-0887-11e6-837a-3718947b932f.png)

**Comment by yeesamson** [comment]
ありがとう。

ログインボタンが分かりやすくなったのと、最初のログインのとき、ソーシャルのアカウントとdekimashitaとつながることが分かりやすくなって、安心感を増した。

![889f33fc-0880-11e6-8d29-bfb158866680](https://cloud.githubusercontent.com/assets/2254390/14732900/a20a8f26-0899-11e6-8de3-e6eb92ff5390.png)
