### ISSUE TITLE
ホームページ

### ISSUE THREAD

**Issue by yeesamson** [chibidata/dekimashita#6]
![homepage](https://cloud.githubusercontent.com/assets/2254390/14093909/617a5966-f58c-11e5-8eb2-2d79bfe14114.png)

登録されたメールアドレスを許可なく第三者に共有することはありません。
私たちもスパムメールは嫌いです。

自動的にメールが届く

各メンバーが返信

集計されたものが
メンバーに届く

SVGアイコン：https://app.box.com/s/wbwukbyagcozd2a83hvgykbcd0fe9jus

**Comment by yeesamson** [comment]
ありがとう。あとは津田さんに渡します。

**Comment by saor1** [comment]
文字の色をグレーにしてちょっと小さくしました。

**Comment by yeesamson** [comment]
<img width="744" alt="screen shot 2016-03-30 at 7 46 08 am" src="https://cloud.githubusercontent.com/assets/2254390/14126380/7d0a69ae-f64b-11e5-884c-e1a8208a8bc4.png">

**Comment by saor1** [comment]
変更しました
![screen shot 2016-03-30 at 12 06 52 pm](https://cloud.githubusercontent.com/assets/9836255/14130718/ec5f5426-f66f-11e5-8170-f22e15de7a5e.png)

**Comment by yoshi-takeda** [comment]
何ができるサービスがいまいちわからないので
ログイン後のページに書いてる↓これを書きませんか？

>dekimashitaは平日の決まった時間にチームメンバーに繰り返し同じ質問をし、
>集められた回答を翌日に一つのメールにまとめて、メンバーに共有します。

**Comment by yoshi-takeda** [comment]
ついでにここの文言修正案
![image](https://cloud.githubusercontent.com/assets/10205763/14159278/f0abe30a-f70f-11e5-9eb3-0ce055bc8af2.png)

なんで？ってのが抜けてたのを補足して、メリットが伝わりやすく
↓↓
dekimashitaを使うとチームメンバーから定期的に状況をアップデートしてもらえます
質問と集計は全て自動で行われるため、管理にかける手間が大幅に減ります

**Comment by yeesamson** [comment]
オッケーです。変えちゃってください。

**Comment by yeesamson** [comment]
第一印象でもあるので、もうちょいフレンドリーにしません？関西弁でもいいし、ロゴもゆるいし、話し言葉で書きたい。

**Comment by yeesamson** [comment]
メールに返信するだけで、今日だれが、何をしたか分かるシンプルなシステム。メンバーがどこどこのページにいってもらって、ユーザー登録して、ログインして、入力することもありません。BETA期間中は無料です。

はどうでしょうか。売りはシンプル。

**Comment by saor1** [comment]
ログイン前画面の青い説明文は↑のサムソン案、
ログイン後トップページの青い説明文は↑の竹田さん案に差し替えました。
あとはdekimashita.comをdekimashitaに統一。

**Comment by yeesamson** [comment]
長すぎたので、省略しました。ファイナルアンサー。

<img width="934" alt="screen shot 2016-03-31 at 15 35 59" src="https://cloud.githubusercontent.com/assets/2254390/14167438/54294b8e-f756-11e5-9706-177b1147860e.png">
