### ISSUE TITLE
フィードバックを集める仕組みを入れる

### ISSUE THREAD

**Issue by yoshi-takeda** [chibidata/dekimashita#63]
まずはなにをどんなタイミングで集めたいのか考える

**Comment by yeesamson** [comment]
これまでいくつかサービスを世に送り出してきたが、フィードバックはそう集まらないものだと思います。いまあるのはガイドページのヘルプフォームとtwitterがあります。これにGAとマネシスがあれば十分かと。

それ以外のフィードバック、それぞれのメンバーが聞いた話しとか、そういうものが貯められる箱はあってもいいかもしれないですね。ここはエネルギーを費やしてもなかなか集まらない。

**Comment by yoshi-takeda** [comment]
ok、じゃあこいつは閉じます
たしかに来ない
