### ISSUE TITLE
USAGEデータを見える化する(GA、マネシスでの表示など)

### ISSUE THREAD

**Issue by yoshi-takeda** [chibidata/dekimashita#64]
まずはどんな項目を見たいのか考える

**Comment by yeesamson** [comment]
一日何通質問メールが送られているのか。（私たちのKPI）
新規登録する際にslackにお知らせが飛ばす。
アクティブユーザー、非アクティブユーザーが分かる指標
たとえば、新規登録したが、質問メールを送っていないユーザーに対して連絡が取れると利用促進ができるようになります。

USAGEも今まで時間をかけてやったものの、あまり使ってないとこなので、拡散方法に時間を使ったほうがいいかもしれない。

**Comment by yoshi-takeda** [comment]
DBから集計できるもので見たいもの

集計値
・チームメンバーの平均人数（グロースの計画のため
・チームメンバー数の合計（KPI
・チームメンバー数の推移（どれくらいで達成できそうか見るため

セグメント
・送信設定がOFFになってから○○日たっている管理者（リテンション
~~・返信率が○○%未満のチーム（無駄が多い、最適化を勧めたい、運用コストも下がる~~
~~　※と思ったけどそれ知られてるとわかったら気持ち悪いと思われそうなので要らない~~

その他（単純に好奇心）
・質問、回答メールの時間、いつが多いのか

あとUI改善系が何個かありそうなので思いついたら書きます
ここらへんはSQLで簡単にかけるのでそれほど負荷じゃない

**Comment by yoshi-takeda** [comment]
https://github.com/chibidata/dekimashita/issues/61　に統合。マネシスで表示する前提にする
