### ISSUE TITLE
集計されたメールのプレビューと編集

### ISSUE THREAD

**Issue by yeesamson** [chibidata/dekimashita#7]
管理者が、集計されたメールが一斉配信される前に確認ができ、コメントや編集ができるようにする。

![answer](https://cloud.githubusercontent.com/assets/2254390/14094242/3ba3b50e-f58f-11e5-95b7-379e3020540f.png)

**Comment by yeesamson** [comment]
![edit](https://cloud.githubusercontent.com/assets/2254390/14162637/a624e2c8-f728-11e5-8947-60925b85bfb5.png)

@saor1 あとこのページだけ、お願いします。

**Comment by saor1** [comment]
変更しました◎

**Comment by yeesamson** [comment]
きれいになりました。ありがとう！
