### ISSUE TITLE
faviconが欲しぃ

### ISSUE THREAD

**Issue by yoshi-takeda** [chibidata/dekimashita#8]
faviconが欲しぃ :family: 

![image](https://cloud.githubusercontent.com/assets/10205763/14096183/9d925f4c-f5a1-11e5-97e6-8d419e3f6c30.png)

**Comment by yoshi-takeda** [comment]
test

**Comment by yeesamson** [comment]
@saor1 が着手してくれるそうです。

**Comment by saor1** [comment]
シルエット的なやつです。
![screen shot 2016-03-29 at 3 52 39 pm](https://cloud.githubusercontent.com/assets/9836255/14100165/62258dd8-f5c6-11e5-929b-564240202737.png)

**Comment by saor1** [comment]
![screen shot 2016-03-29 at 5 57 19 pm](https://cloud.githubusercontent.com/assets/9836255/14102803/c28224f0-f5d7-11e5-8498-fd18d0b168a4.png)
変更

**Comment by saor1** [comment]
bootstrapでいろんなデバイス向けfaviconを仕込むタグを入れてくれているが、いまのところ32*32の普通のfavicon.icoだけ入れた状態

**Comment by yeesamson** [comment]
いいと思います。見られてますね。
ありがとう。
