### ISSUE TITLE
設定からキャンセルするとON OFFボタン消える。

### ISSUE THREAD

**Issue by yeesamson** [chibidata/dekimashita#9]
![kieru](https://cloud.githubusercontent.com/assets/2254390/14096665/6860c152-f5a5-11e5-8724-c7e0e626338b.gif)

リロードするとONボタンが戻る。これは@macha3162 さんからすぐ直せるかね。

**Comment by macha3162** [comment]
Turbolinksという機能と競合していたのでTurbolinksをOFFしました。
対応完了です。
